/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import static forms.FirstPage.ManagerId;
import org.xml.sax.Attributes;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class AdminHome1 extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome1
     */
    public AdminHome1() {
        initComponents();
        jPanelRemoveUser.setVisible(false);
        jPanelRemoveManager.setVisible(false);
       // jPanelChange.setBackground(Color.BLUE);
       //jPanelAdd.setBackground(Color.ORANGE);
       //jPanelHome.setBackground(Color.getHSBColor(4.5f, 6.7f, 8.8f));
        //setBackground(Color.BLACK);
        jLabel12.setBackground(Color.red);
        jLabel13.setBackground(Color.red);
        
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root"); 
           //PreparedStatement ps = con.prepareStatement("select a.vehicle_id,v.vname,v.vehicle_type,a.date,a.start_time,a.duration,a.status,a.customer_id from availability as a left join vehicle as v on vehicle_id = vid and cutomer_id is null");
           PreparedStatement ps = con.prepareStatement("select * from vehicle_feedback");
           ResultSet rs = ps.executeQuery();
           DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
           while(rs.next())
           {
               Object obj[] = {rs.getInt(1),rs.getInt(2),rs.getString(3),rs.getString(4)};
               dtm.addRow(obj);
               
           }
       }catch(ClassNotFoundException | SQLException e){
           e.printStackTrace();
       }
        
         try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root"); 
           //PreparedStatement ps = con.prepareStatement("select a.vehicle_id,v.vname,v.vehicle_type,a.date,a.start_time,a.duration,a.status,a.customer_id from availability as a left join vehicle as v on vehicle_id = vid and cutomer_id is null");
           PreparedStatement ps = con.prepareStatement("select * from feedbackform");
           ResultSet rs = ps.executeQuery();
           DefaultTableModel dtm = (DefaultTableModel)jTable2.getModel();
           while(rs.next())
           {
               Object obj[] = {rs.getInt(1),rs.getInt(2),rs.getString(3)};
               dtm.addRow(obj);
           }
       }catch(ClassNotFoundException | SQLException e){
           e.printStackTrace();
       }
         
         try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root"); 
           PreparedStatement ps = con.prepareStatement("select v.ownerId,a.vehicle_id,v.vname,v.vehicle_type,a.date,a.start_time,a.duration,a.status,a.price from availability as a,vehicle as v where vehicle_id = vid and status like '%available%' order by date");
           ResultSet rs = ps.executeQuery();
           DefaultTableModel dtm = (DefaultTableModel)jTable3.getModel();
           while(rs.next())
           {
               Object obj[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getDate(5),rs.getTime(6),rs.getInt(7),rs.getString(8),rs.getInt(9)};
               dtm.addRow(obj);
               
           }
       }catch(ClassNotFoundException | SQLException e){
           e.printStackTrace();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jPanelRemoveUser = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIdUser = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanelRemoveManager = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIdManager = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanelChange = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtManagerId = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnChangePass = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtConfirmPass = new javax.swing.JPasswordField();
        jPanelAdd = new javax.swing.JPanel();
        txtPass1 = new javax.swing.JPasswordField();
        txtManagerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtManagerId2 = new javax.swing.JTextField();
        jPanelComplaint = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanelFeedback = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelVehiclesAvailability = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanelHome.setOpaque(false);

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Delete User record");

        jLabel7.setText("User Id");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Close-icon.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/Status-dialog-error-icon.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRemoveUserLayout = new javax.swing.GroupLayout(jPanelRemoveUser);
        jPanelRemoveUser.setLayout(jPanelRemoveUserLayout);
        jPanelRemoveUserLayout.setHorizontalGroup(
            jPanelRemoveUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoveUserLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addComponent(jTextFieldIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRemoveUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRemoveUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRemoveUserLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRemoveUserLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanelRemoveUserLayout.setVerticalGroup(
            jPanelRemoveUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoveUserLayout.createSequentialGroup()
                .addGroup(jPanelRemoveUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelRemoveUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanelRemoveUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Delete Manager record");

        jLabel10.setText("Manager Id");

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Close-icon.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/Status-dialog-error-icon.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRemoveManagerLayout = new javax.swing.GroupLayout(jPanelRemoveManager);
        jPanelRemoveManager.setLayout(jPanelRemoveManagerLayout);
        jPanelRemoveManagerLayout.setHorizontalGroup(
            jPanelRemoveManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoveManagerLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel10)
                .addGap(45, 45, 45)
                .addComponent(jTextFieldIdManager, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRemoveManagerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRemoveManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRemoveManagerLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRemoveManagerLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(30, 30, 30))))
        );
        jPanelRemoveManagerLayout.setVerticalGroup(
            jPanelRemoveManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoveManagerLayout.createSequentialGroup()
                .addGroup(jPanelRemoveManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelRemoveManagerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanelRemoveManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldIdManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jLabel12.setBackground(new java.awt.Color(255, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("    Delete User Record");
        jLabel12.setOpaque(true);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("    Delete Manager Record");
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jPanelRemoveManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addComponent(jPanelRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jPanelRemoveManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );

        jTabbedPane1.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/forms/home-icon.png")), jPanelHome); // NOI18N

        jPanelChange.setBackground(new java.awt.Color(255, 255, 255));
        jPanelChange.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("           id");
        jLabel1.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("Password");
        jLabel3.setOpaque(true);

        btnChangePass.setBackground(new java.awt.Color(204, 255, 204));
        btnChangePass.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnChangePass.setForeground(new java.awt.Color(153, 0, 0));
        btnChangePass.setText("Change");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 0));
        jLabel15.setText("Confirm Password");
        jLabel15.setOpaque(true);

        javax.swing.GroupLayout jPanelChangeLayout = new javax.swing.GroupLayout(jPanelChange);
        jPanelChange.setLayout(jPanelChangeLayout);
        jPanelChangeLayout.setHorizontalGroup(
            jPanelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChangeLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(114, 114, 114)
                .addGroup(jPanelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChangePass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(418, Short.MAX_VALUE))
        );
        jPanelChangeLayout.setVerticalGroup(
            jPanelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChangeLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChangePass)
                .addGap(128, 128, 128))
        );

        jTabbedPane1.addTab("Change Manager Password", new javax.swing.ImageIcon(getClass().getResource("/forms/change.png")), jPanelChange); // NOI18N

        jPanelAdd.setBackground(new java.awt.Color(51, 51, 51));
        jPanelAdd.setForeground(new java.awt.Color(0, 204, 0));
        jPanelAdd.setOpaque(false);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Password");
        jLabel4.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("id");
        jLabel2.setOpaque(true);

        btnSubmit.setBackground(new java.awt.Color(255, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Name");
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout jPanelAddLayout = new javax.swing.GroupLayout(jPanelAdd);
        jPanelAdd.setLayout(jPanelAddLayout);
        jPanelAddLayout.setHorizontalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddLayout.createSequentialGroup()
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                                .addComponent(txtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddLayout.createSequentialGroup()
                                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtManagerId2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(270, 270, 270))
        );
        jPanelAddLayout.setVerticalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtManagerId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnSubmit)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add new Manger", new javax.swing.ImageIcon(getClass().getResource("/images/Actions-contact-new-icon.png")), jPanelAdd); // NOI18N

        jPanelComplaint.setOpaque(false);
        jPanelComplaint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelComplaintMouseClicked(evt);
            }
        });
        jPanelComplaint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 255, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "complaint Id", "user Id", "Vehicle_Id", "Complaint"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanelComplaint.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 767, 400));

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jButton5.setText("Remove Complaint");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanelComplaint.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 250, -1));

        jTabbedPane1.addTab("Complaints", new javax.swing.ImageIcon(getClass().getResource("/images/complaint.png")), jPanelComplaint); // NOI18N

        jPanelFeedback.setOpaque(false);
        jPanelFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelFeedbackMouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 153));
        jButton4.setText("Remove Feedback");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(0, 204, 51));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "User Id", "Feedback"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jScrollPane4.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanelFeedbackLayout = new javax.swing.GroupLayout(jPanelFeedback);
        jPanelFeedback.setLayout(jPanelFeedbackLayout);
        jPanelFeedbackLayout.setHorizontalGroup(
            jPanelFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFeedbackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanelFeedbackLayout.setVerticalGroup(
            jPanelFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFeedbackLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Feedback", jPanelFeedback);

        jPanelVehiclesAvailability.setOpaque(false);
        jPanelVehiclesAvailability.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelVehiclesAvailabilityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelVehiclesAvailabilityMouseEntered(evt);
            }
        });
        jPanelVehiclesAvailability.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Provider", "Vehicle ID", "Vehicle_name", "Vehicle Type", "date", "start time", "duration", "status", "Price"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        jScrollPane6.setViewportView(jScrollPane5);

        jPanelVehiclesAvailability.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 350));

        jTabbedPane1.addTab("Vehices Availability", new javax.swing.ImageIcon(getClass().getResource("/images/availability.png")), jPanelVehiclesAvailability); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 830, 560));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Putting-Your-Car-into-the-Garage.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1110, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String id = txtManagerId2.getText();
        String name = txtManagerName.getText();
        String password = new String(txtPass1.getPassword());
        if(id.equals(""))
        JOptionPane.showMessageDialog(this, "id field is required");
        else if(name.equals(""))
        JOptionPane.showMessageDialog(this, "name field is required");
        else if(password.equals(""))
        JOptionPane.showMessageDialog(this, "password field is required");
        else
        {

            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root");
                PreparedStatement ps = con.prepareStatement("insert into complaintmanager values(?,?,?)");
                ps.setString(1, id);
                ps.setString(2, password);
                ps.setString(3, name);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record inserted successfully");
            }catch(ClassNotFoundException | SQLException e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        String id = txtManagerId.getText();
        String newPass = new String(txtPass.getPassword());
        String confirmPass = new String(txtConfirmPass.getPassword());
        if(id.equals(""))
            JOptionPane.showMessageDialog(this, "ID field is required");
        else if(newPass.equals(""))
            JOptionPane.showMessageDialog(this, "New password field is required");
        else if(confirmPass.equals(""))
            JOptionPane.showMessageDialog(this, "confirm Password field is required");
        else if(newPass.equals(confirmPass))
        {
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root");
                PreparedStatement ps = con.prepareStatement("update complaintmanager set password = ? where id = ?");
                ps.setString(1,newPass);
                ps.setString(2,id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Password updated succesfully");
            }catch(SQLException | ClassNotFoundException e)
            {
                e.printStackTrace();
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Password and cofirm password doesn't match");
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        jPanelRemoveManager.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        jPanelRemoveUser.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        jPanelRemoveManager.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String id = jTextFieldIdManager.getText();
        if(id.equals(""))
        JOptionPane.showMessageDialog(this, "id field is required");
        else
        {
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root");
                PreparedStatement ps = con.prepareStatement("select * from complaintmanager where id = ?");
                ps.setString(1, id);
                ResultSet rs = ps.executeQuery();
                if(rs.next())
                {
                    PreparedStatement ps1 = con.prepareStatement("delete from complaintmanager where id = ?");
                    ps1.setString(1,id);
                    ps1.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record deleted");
                }
                else
                JOptionPane.showMessageDialog(this, "Invalid ID");

            }catch(ClassNotFoundException | SQLException e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jPanelRemoveUser.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = jTextFieldIdUser.getText();

        if(id.equals(""))
        JOptionPane.showMessageDialog(this, "id field is required");
        else{
            int userId = Integer.parseInt(id);
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root");
                PreparedStatement ps = con.prepareStatement("select * from user where id = ?");
                ps.setInt(1, userId);
                ResultSet rs = ps.executeQuery();
                if(rs.next())
                {
                    PreparedStatement ps1 = con.prepareStatement("delete from user where id = ?");
                    ps1.setInt(1, userId);
                    ps1.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record deleted");
                }
                else
                JOptionPane.showMessageDialog(this, "Invalid ID");

            }catch(ClassNotFoundException | SQLException e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        dispose();
        FirstPage ref = new FirstPage();
        ref.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Do ypu want to delete the complaint", "Warning!!!", JOptionPane.YES_NO_OPTION);
        if(confirm == 0)
        {
        int row = jTable1.getSelectedRow();
        int idToDelete = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());
        System.out.println(idToDelete);
        ((DefaultTableModel)jTable1.getModel()).removeRow(row);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root");
            PreparedStatement ps = con.prepareStatement("delete from vehicle_feedback where complaint_id  = ?");
            ps.setInt(1,idToDelete);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Complaint removed successfully");
        }catch(ClassNotFoundException | SQLException e)
        {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Do ypu want to delete the feedback", "Warning!!!", JOptionPane.YES_NO_OPTION);
        if(confirm == 0)
        {
        int row = jTable2.getSelectedRow();
        int feedbackId =Integer.parseInt(jTable2.getModel().getValueAt(row, 0).toString());
        ((DefaultTableModel)jTable2.getModel()).removeRow(row);
        System.out.println(feedbackId);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root");
            PreparedStatement ps = con.prepareStatement("delete from feedbackform where id = ?");
            ps.setInt(1,feedbackId);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Feedback removed successfully");
          }catch(ClassNotFoundException | SQLException e)
          {
            e.printStackTrace();
          }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
          
    }//GEN-LAST:event_jTabbedPane1MouseClicked
   
    private void jPanelVehiclesAvailabilityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVehiclesAvailabilityMouseClicked
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root"); 
           PreparedStatement ps = con.prepareStatement("select v.ownerId,a.vehicle_id,v.vname,v.vehicle_type,a.date,a.start_time,a.duration,a.status,a.price from availability as a,vehicle as v where vehicle_id = vid and status like '%available%' order by date");
           ResultSet rs = ps.executeQuery();
           DefaultTableModel dtm = (DefaultTableModel)jTable3.getModel();
           while(rs.next())
           {
               Object obj[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getDate(5),rs.getTime(6),rs.getInt(7),rs.getString(8),rs.getInt(9)};
               dtm.addRow(obj);
               
           }
       }catch(ClassNotFoundException | SQLException e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_jPanelVehiclesAvailabilityMouseClicked

    private void jPanelComplaintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelComplaintMouseClicked
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root"); 
           //PreparedStatement ps = con.prepareStatement("select a.vehicle_id,v.vname,v.vehicle_type,a.date,a.start_time,a.duration,a.status,a.customer_id from availability as a left join vehicle as v on vehicle_id = vid and cutomer_id is null");
           PreparedStatement ps = con.prepareStatement("select * from vehicle_feedback");
           ResultSet rs = ps.executeQuery();
           DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
           while(rs.next())
           {
               Object obj[] = {rs.getInt(1),rs.getInt(2),rs.getString(3),rs.getString(4)};
               dtm.addRow(obj);
               
           }
       }catch(ClassNotFoundException | SQLException e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_jPanelComplaintMouseClicked

    private void jPanelFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFeedbackMouseClicked
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root"); 
           //PreparedStatement ps = con.prepareStatement("select a.vehicle_id,v.vname,v.vehicle_type,a.date,a.start_time,a.duration,a.status,a.customer_id from availability as a left join vehicle as v on vehicle_id = vid and cutomer_id is null");
           PreparedStatement ps = con.prepareStatement("select * from feedbackform");
           ResultSet rs = ps.executeQuery();
           DefaultTableModel dtm = (DefaultTableModel)jTable2.getModel();
           while(rs.next())
           {
               Object obj[] = {rs.getInt(1),rs.getInt(2),rs.getString(3)};
               dtm.addRow(obj);
           }
       }catch(ClassNotFoundException | SQLException e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_jPanelFeedbackMouseClicked

    private void jPanelVehiclesAvailabilityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVehiclesAvailabilityMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelVehiclesAvailabilityMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAdd;
    private javax.swing.JPanel jPanelChange;
    private javax.swing.JPanel jPanelComplaint;
    private javax.swing.JPanel jPanelFeedback;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelRemoveManager;
    private javax.swing.JPanel jPanelRemoveUser;
    private javax.swing.JPanel jPanelVehiclesAvailability;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextFieldIdManager;
    private javax.swing.JTextField jTextFieldIdUser;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JTextField txtManagerId;
    private javax.swing.JTextField txtManagerId2;
    private javax.swing.JTextField txtManagerName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPass1;
    // End of variables declaration//GEN-END:variables
}
