/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forms;

import org.netbeans.lib.awtextra;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.netbeans.lib.awtextra ;
/**
 *
 * @author LENOVOPC
 */
public class UserHome extends javax.swing.JFrame {

    /**
     * Creates new form Panels
     */
    public UserHome() {
        initComponents();
        jPanelHome.setBackground(Color.black);
        
       jTextField1.setText(Integer.toString(FirstPage.userId));
       try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root"); 
           PreparedStatement ps = con.prepareStatement("select a.vehicle_id,v.vname,v.vehicle_type,a.date,a.start_time,a.duration,a.status,a.price from availability as a,vehicle as v where vehicle_id = vid and status like '%available%' order by date");
           ResultSet rs = ps.executeQuery();
           DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
           while(rs.next())
           {
               Object obj[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getDate(4),rs.getTime(5),rs.getInt(6),rs.getString(7),rs.getInt(8)};
               dtm.addRow(obj);
               
           }
       }catch(ClassNotFoundException | SQLException e){
           e.printStackTrace();
       }
       
       try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root"); 
           PreparedStatement ps = con.prepareStatement("select a.vehicle_id,v.vname,v.vehicle_type,a.date,a.start_time,a.duration from availability as a , vehicle as v where vehicle_id = vid and customer_id = "+userId);
           ResultSet rs = ps.executeQuery();
           DefaultTableModel dtm = (DefaultTableModel)jTable2.getModel();
           while(rs.next())
           {
               Object obj[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getDate(4),rs.getTime(5),rs.getInt(6)};
               dtm.addRow(obj);
             
           }
       }catch(ClassNotFoundException | SQLException e){
           e.printStackTrace();
       }
//      Thread th1 = new  Thread("label1");
//      Thread th2 = new  Thread("label1");
//      Thread th3 = new  Thread("label1");
//      th1.start();
//      th2.start();
//      th3.start();
    }
    final static int userId = FirstPage.userId;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanelVehiclesAvailability = new javax.swing.JPanel();
        btnBook = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelAdd = new javax.swing.JPanel();
        jPanelFeedbackAdd = new javax.swing.JPanel();
        txtStartTime = new javax.swing.JTextField();
        jLabelVehicleId1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtVehicleId = new javax.swing.JTextField();
        txtDuration = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSubmitAdd = new javax.swing.JButton();
        jPanelFeedback = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonFeedback = new javax.swing.JButton();
        jPanelChangePassword = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtOldPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnUpdatePassword = new javax.swing.JButton();
        jPanelComplaint = new javax.swing.JPanel();
        jLabelVehicleId2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtVehicleId1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaComplaint = new javax.swing.JTextArea();
        btnUploadComplaint = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane.setBackground(new java.awt.Color(51, 51, 255));

        jLabel11.setBackground(new java.awt.Color(255, 0, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ducati-motorcycle-animated-gif-2.gif"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 51));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bike.gif"))); // NOI18N
        jLabel12.setText("2");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/39420.gif"))); // NOI18N

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 246, Short.MAX_VALUE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jTabbedPane.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/forms/home-icon.png")), jPanelHome); // NOI18N

        jPanelVehiclesAvailability.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBook.setBackground(new java.awt.Color(0, 0, 255));
        btnBook.setForeground(new java.awt.Color(0, 204, 0));
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        jPanelVehiclesAvailability.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "vehicle Id", "Vehicle Name", "Vehicle Type", "Date", "Start time", "Duration", "Status", "Price"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanelVehiclesAvailability.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 360));

        jTabbedPane.addTab("Vehices Availability", new javax.swing.ImageIcon(getClass().getResource("/images/availability.png")), jPanelVehiclesAvailability); // NOI18N

        jLabelVehicleId1.setText("Vehicle Id");

        jLabel6.setText("Date");

        jLabel7.setText("Start time");

        jLabel8.setText("Duration");

        btnSubmitAdd.setText("Upload");
        btnSubmitAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFeedbackAddLayout = new javax.swing.GroupLayout(jPanelFeedbackAdd);
        jPanelFeedbackAdd.setLayout(jPanelFeedbackAddLayout);
        jPanelFeedbackAddLayout.setHorizontalGroup(
            jPanelFeedbackAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFeedbackAddLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanelFeedbackAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFeedbackAddLayout.createSequentialGroup()
                        .addGroup(jPanelFeedbackAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabelVehicleId1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(105, 105, 105)
                        .addGroup(jPanelFeedbackAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStartTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDuration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(286, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFeedbackAddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmitAdd)
                .addGap(316, 316, 316))
        );
        jPanelFeedbackAddLayout.setVerticalGroup(
            jPanelFeedbackAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFeedbackAddLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanelFeedbackAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVehicleId1)
                    .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFeedbackAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFeedbackAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnSubmitAdd)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAddLayout = new javax.swing.GroupLayout(jPanelAdd);
        jPanelAdd.setLayout(jPanelAddLayout);
        jPanelAddLayout.setHorizontalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddLayout.createSequentialGroup()
                    .addGap(0, 34, Short.MAX_VALUE)
                    .addComponent(jPanelFeedbackAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelAddLayout.setVerticalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
            .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelFeedbackAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane.addTab("Add", new javax.swing.ImageIcon(getClass().getResource("/Actions-contact-new-icon.png")), jPanelAdd); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonFeedback.setBackground(new java.awt.Color(0, 0, 204));
        jButtonFeedback.setText("Submit");
        jButtonFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeedbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFeedbackLayout = new javax.swing.GroupLayout(jPanelFeedback);
        jPanelFeedback.setLayout(jPanelFeedbackLayout);
        jPanelFeedbackLayout.setHorizontalGroup(
            jPanelFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFeedbackLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jButtonFeedback)
                .addContainerGap(444, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFeedbackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
        );
        jPanelFeedbackLayout.setVerticalGroup(
            jPanelFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFeedbackLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButtonFeedback)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Feedback", new javax.swing.ImageIcon(getClass().getResource("/forms/feedback-icon.png")), jPanelFeedback); // NOI18N

        jLabel2.setText("Old Password");

        jLabel3.setText("New Password");

        jLabel4.setText("Confirm Password");

        jLabel5.setText("Id");

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnUpdatePassword.setText("Update");
        btnUpdatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelChangePasswordLayout = new javax.swing.GroupLayout(jPanelChangePassword);
        jPanelChangePassword.setLayout(jPanelChangePasswordLayout);
        jPanelChangePasswordLayout.setHorizontalGroup(
            jPanelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChangePasswordLayout.createSequentialGroup()
                .addGroup(jPanelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelChangePasswordLayout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jLabel4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChangePasswordLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(143, 143, 143)
                .addGroup(jPanelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdatePassword)
                    .addGroup(jPanelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txtNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(jTextField1))))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanelChangePasswordLayout.setVerticalGroup(
            jPanelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChangePasswordLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(62, 62, 62)
                .addComponent(btnUpdatePassword)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Change Password", new javax.swing.ImageIcon(getClass().getResource("/forms/change.png")), jPanelChangePassword); // NOI18N

        jLabelVehicleId2.setText("Vehicle Id");

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("                           Complaint");
        jLabel9.setOpaque(true);

        jTextAreaComplaint.setColumns(20);
        jTextAreaComplaint.setRows(5);
        jScrollPane3.setViewportView(jTextAreaComplaint);

        btnUploadComplaint.setBackground(new java.awt.Color(0, 255, 0));
        btnUploadComplaint.setText("Upload");
        btnUploadComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadComplaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelComplaintLayout = new javax.swing.GroupLayout(jPanelComplaint);
        jPanelComplaint.setLayout(jPanelComplaintLayout);
        jPanelComplaintLayout.setHorizontalGroup(
            jPanelComplaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComplaintLayout.createSequentialGroup()
                .addGroup(jPanelComplaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComplaintLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUploadComplaint))
                    .addGroup(jPanelComplaintLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanelComplaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelComplaintLayout.createSequentialGroup()
                                .addComponent(jLabelVehicleId2)
                                .addGap(79, 79, 79)
                                .addComponent(txtVehicleId1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelComplaintLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelComplaintLayout.setVerticalGroup(
            jPanelComplaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComplaintLayout.createSequentialGroup()
                .addComponent(btnUploadComplaint)
                .addGap(4, 4, 4)
                .addGroup(jPanelComplaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVehicleId2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        jTabbedPane.addTab("Complaint", new javax.swing.ImageIcon(getClass().getResource("/forms/complaint.png")), jPanelComplaint); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle ID", "vehicle name", "Vehicle Type", "Date", "Start Time", "Duration"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 255, 153));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        jTabbedPane.addTab("My Bookings", jPanel1);

        getContentPane().add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 580));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGOUT1.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 100, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        FirstPage ref = new FirstPage();
        ref.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnUploadComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadComplaintActionPerformed

        String vehicleId = txtVehicleId1.getText();
        String complaint = jTextAreaComplaint.getText();
        
        if(vehicleId.equals(""))
        JOptionPane.showMessageDialog(this, "Vehicle Id field is required");
        else if(complaint.equals(""))
        JOptionPane.showMessageDialog(this, "complaint field is required");
        else
        {
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root");
                PreparedStatement ps = con.prepareStatement("insert into vehicle_feedback(user_id,vehicle_id,complaint) values(?,?,?)");
                ps.setInt(1,userId);
                ps.setString(2, vehicleId);
                ps.setString(3,complaint);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Done");

                txtVehicleId1.setText("");
                jTextAreaComplaint.setText("");
                
            }
            catch(ClassNotFoundException|SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnUploadComplaintActionPerformed

    private void btnUpdatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePasswordActionPerformed

        String oldPass = new String(txtOldPassword.getPassword());
        String newPass = new String(txtNewPassword.getPassword());
        String confirmPass = new String(txtConfirmPassword.getPassword());
        if(oldPass.equals(""))
        JOptionPane.showMessageDialog(this, "Old password field is required");
        else if(newPass.equals(""))
        JOptionPane.showMessageDialog(this, "New password field is required");
        else if(confirmPass.equals(""))
        JOptionPane.showMessageDialog(this, "confirm Password field is required");
        else{
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root");
                PreparedStatement ps = con.prepareStatement("select * from user where id = ? and password = ?");
                ps.setInt(1,userId);
                ps.setString(2,oldPass);
                ResultSet rs = ps.executeQuery();
                if(rs.next())
                {
                    if(newPass.equals(confirmPass))
                    {
                        PreparedStatement ps1 = con.prepareStatement("update user set password = ? where id = ?");
                        ps1.setString(1, newPass);
                        ps1.setInt(2, userId);
                        ps1.executeUpdate();
                        JOptionPane.showMessageDialog(this,"hey thats great !!! its changed");

                    }
                    else
                    JOptionPane.showMessageDialog(this,"new pass & confirm new pwd are not same");
                }
                else
                JOptionPane.showMessageDialog(this,"old password is incorrect");
            }catch(SQLException | ClassNotFoundException e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnUpdatePasswordActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeedbackActionPerformed

        String feedback = jTextArea1.getText();
        if(feedback.equals(""))
        JOptionPane.showMessageDialog(this, "feedback field shoul not be empty");
        else
        {
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root");
                PreparedStatement ps = con.prepareStatement("insert into feedbackform(user_id,feedback) values(?,?)");
                ps.setInt(1,userId);
                ps.setString(2, feedback);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Done");
                jTextField1.setText("");
                jTextArea1.setText("");
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonFeedbackActionPerformed

    private void btnSubmitAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAddActionPerformed
        String vehicleId = txtVehicleId.getText();
        //Date Picker Logic
        String startTime = txtStartTime.getText();
        String duration = txtDuration.getText();
        if(vehicleId.equals(""))
        JOptionPane.showMessageDialog(this, "vehicle Id field is required");
        else if(startTime.equals(""))
        JOptionPane.showMessageDialog(this, "start Time field is required");
        else if(duration.equals(""))
        JOptionPane.showMessageDialog(this, "duration field is required");
        else{
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root");
                PreparedStatement ps = con.prepareStatement("insert into availability() values(?,?,?,?,?,?,?)");
                ps.setInt(1,userId);
                ps.setString(2, vehicleId);
                // ps.setString(3, new Date().toString());
                ps.setString(4, startTime);
                ps.setString(5, duration);
                ps.setString(6,"No");
                ps.setString(7, null);
                ps.executeUpdate();
            }catch(ClassNotFoundException | SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSubmitAddActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        
        int row = jTable1.getSelectedRow();
        System.out.println("row = "+row);
        String vid =  jTable1.getModel().getValueAt(row, 0).toString();
        String date = jTable1.getModel().getValueAt(row, 3).toString();
//        DateFormat df = new SimpleDateFormat("yyyy-mm-DD");
//        try {
//            Date d = (Date) df.parse(date);
//        } catch (ParseException ex) {
//            Logger.getLogger(UserHome.class.getName()).log(Level.SEVERE, null, ex);
//        }
        ((DefaultTableModel)jTable1.getModel()).removeRow(row);
        
        
        System.out.println("id = "+vid);
        System.out.println("Date = "+date);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root");
            PreparedStatement ps1 = con.prepareStatement("update availability set status = ? , customer_id = ? where vehicle_id = ? and date = ?");
            ps1.setString(1, "booked");
            ps1.setInt(2, userId);
            ps1.setString(3, vid);
            ps1.setString(4,date);
            ps1.executeUpdate();
        }catch(ClassNotFoundException | SQLException e){
            e.printStackTrace();
       }
    }//GEN-LAST:event_btnBookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row = jTable2.getSelectedRow();
        String vid = jTable2.getModel().getValueAt(row, 0).toString();
        String date = jTable2.getModel().getValueAt(row, 3).toString();
        DateFormat df = new SimpleDateFormat("yyyy-mm-DD");
        //Date d = df.parse(date);
        System.out.println(vid);
        ((DefaultTableModel)jTable2.getModel()).removeRow(row);
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scooter_landing","root","root");
            PreparedStatement ps1 = con.prepareStatement("update availability set status = ? , customer_id = ? where vehicle_id = ? and date = ?");
            ps1.setString(1, "available");
            ps1.setInt(2, userId);
            ps1.setString(3, vid);
            ps1.setString(4,date);
            ps1.executeUpdate();
        }catch(ClassNotFoundException | SQLException e){
            e.printStackTrace();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnSubmitAdd;
    private javax.swing.JButton btnUpdatePassword;
    private javax.swing.JButton btnUploadComplaint;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonFeedback;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelVehicleId1;
    private javax.swing.JLabel jLabelVehicleId2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAdd;
    private javax.swing.JPanel jPanelChangePassword;
    private javax.swing.JPanel jPanelComplaint;
    private javax.swing.JPanel jPanelFeedback;
    private javax.swing.JPanel jPanelFeedbackAdd;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelVehiclesAvailability;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaComplaint;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtOldPassword;
    private javax.swing.JTextField txtStartTime;
    private javax.swing.JTextField txtVehicleId;
    private javax.swing.JTextField txtVehicleId1;
    // End of variables declaration//GEN-END:variables
}
